# Spring Cloud Kafka Streams 설정
spring.cloud:
  function:
    definition: ecoService;landService
  stream:
    bindings:
      ecoService-in-0:
        destination: eco-news
      landService-in-0:
        destination: land-news
    kafka:
      bindings:
        ecoService-in-0:
          consumer:
            configuration:
              value:
                deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        landService-in-0:
          consumer:
            configuration:
              value:
                deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      binder:
        brokers:
          - localhost:9092

spring:
  batch:
    job:
      enabled: false # 서버 재시작시 배치 자동실행 방지
  datasource: # batch를 사용하기 위해 h2 database 사용
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;